definitions:
  cian_web.schemas.ErrorResponseSchema:
    properties:
      errors:
        items:
          title: errors
          type: object
        title: errors
        type: array
      message:
        title: message
        type: string
    type: object
  my_offers.entities.get_offers.AuctionSchema:
    properties:
      bet:
        description: Текущая ставка аукциона
        format: int64
        title: bet
        type: integer
      districtPlace:
        description: Позиция конкуренции по району
        format: int64
        title: district_place
        type: integer
      homePlace:
        description: Позиция конкуренции по дому
        format: int64
        title: home_place
        type: integer
    type: object
  my_offers.entities.get_offers.FilterSchema:
    properties:
      dealType:
        description: Тип сделки
        enum:
        - rent
        - sale
        type: string
        x-rent: Аренда
        x-sale: Продажа
      hasPhoto:
        description: Только с фото
        title: has_photo
        type: boolean
      isInHiddenBase:
        description: Только видимые агентам
        title: is_in_hidden_base
        type: boolean
      isManual:
        description: Только ручные
        title: is_manual
        type: boolean
      offerType:
        description: Тип объявления
        enum:
        - commercial
        - flat
        - newobject
        - suburban
        type: string
        x-commercial: Коммерческая
        x-flat: Жилая
        x-newobject: Новостройки
        x-suburban: Загородная
      searchText:
        description: Полнотекстовый поиск по объявлению
        title: search_text
        type: string
      services:
        description: Тип размещения
        items:
          enum:
          - auction
          - calltracking
          - free
          - highlight
          - paid
          - premium
          - top3
          type: string
          x-auction: ''
          x-calltracking: ''
          x-free: ''
          x-highlight: ''
          x-paid: ''
          x-premium: ''
          x-top3: ''
        title: services
        type: array
      sortType:
        description: Тип сортировки
        enum:
        - byAreaMax
        - byAreaMin
        - byOfferId
        - byPriceForMeter
        - byPriceMax
        - byPriceMin
        - byStreet
        - byWalkTime
        type: string
        x-byAreaMax: 'По площади: возрастающая'
        x-byAreaMin: 'По площади: убывающая'
        x-byOfferId: По ID объявления
        x-byPriceForMeter: По цене за метр
        x-byPriceMax: 'По цене: возрастающая'
        x-byPriceMin: 'По цене: убывающая'
        x-byStreet: По улице
        x-byWalkTime: По времени до метро
      statusTab:
        description: Вкладка
        enum:
        - active
        - archived
        - declined
        - notActive
        type: string
        x-active: Активные
        x-archived: Архив
        x-declined: Отклоненные
        x-notActive: Неактивные
      subAgentIds:
        description: Список сотрудников (только для мастрер аккаунтов)
        items:
          format: int64
          title: sub_agent_ids
          type: integer
        title: sub_agent_ids
        type: array
    required:
    - statusTab
    type: object
  my_offers.entities.get_offers.GetOfferSchema:
    properties:
      auction:
        $ref: '#/definitions/my_offers.entities.get_offers.AuctionSchema'
        description: Данные об аукционе по объявлению
      createdAt:
        description: Дата подачи объявления
        format: date-time
        title: created_at
        type: string
      features:
        description: 'Ключевые параметры: комиссии, бонусы, свободная продажа, ипотека'
        items:
          title: features
          type: string
        title: features
        type: array
      geo:
        $ref: '#/definitions/my_offers.entities.offer_view_model.OfferGeoSchema'
        description: Гео
      id:
        description: ID объявления
        format: int64
        title: id
        type: integer
      isFromPackage:
        description: ' Флаг ''из пакета'''
        title: is_from_package
        type: boolean
      isManual:
        description: ' Флаг ''из импорта'''
        title: is_manual
        type: boolean
      isPublicationTimeEnds:
        description: ' Флаг ''меньше суток до конца публикации'''
        title: is_publication_time_ends
        type: boolean
      mainPhotoUrl:
        description: Основаная фотография объекта
        title: main_photo_url
        type: string
      priceInfo:
        $ref: '#/definitions/my_offers.entities.offer_view_model.PriceInfoSchema'
        description: Инофрмация о цене
      publishFeatures:
        description: 'Параметры публикации: сколько осталось, автопродление'
        items:
          title: publish_features
          type: string
        title: publish_features
        type: array
      statistics:
        $ref: '#/definitions/my_offers.entities.get_offers.StatisticsSchema'
        description: Статистика по объявлению
      subagent:
        $ref: '#/definitions/my_offers.entities.offer_view_model.SubagentSchema'
        description: Сабагент
      title:
        description: Заголовок объявления
        title: title
        type: string
      url:
        description: URL объявления
        title: url
        type: string
      vas:
        description: Список VAS'ов
        items:
          enum:
          - auction
          - colorized
          - payed
          - premium
          - top3
          type: string
          x-auction: ''
          x-colorized: ''
          x-payed: ''
          x-premium: ''
          x-top3: ''
        title: vas
        type: array
    required:
    - createdAt
    - features
    - geo
    - id
    - isFromPackage
    - isManual
    - isPublicationTimeEnds
    - priceInfo
    - url
    - vas
    type: object
  my_offers.entities.get_offers.GetOffersRequestSchema:
    properties:
      filters:
        $ref: '#/definitions/my_offers.entities.get_offers.FilterSchema'
        description: Параметры фильтрации
      pagination:
        $ref: '#/definitions/my_offers.entities.get_offers.PaginationSchema'
        description: Параметры страницы
      sort:
        description: Сортировка
        enum:
        - byAreaMax
        - byAreaMin
        - byOfferId
        - byPriceForMeter
        - byPriceMax
        - byPriceMin
        - byStreet
        - byWalkTime
        type: string
        x-byAreaMax: 'По площади: возрастающая'
        x-byAreaMin: 'По площади: убывающая'
        x-byOfferId: По ID объявления
        x-byPriceForMeter: По цене за метр
        x-byPriceMax: 'По цене: возрастающая'
        x-byPriceMin: 'По цене: убывающая'
        x-byStreet: По улице
        x-byWalkTime: По времени до метро
    required:
    - filters
    type: object
  my_offers.entities.get_offers.GetOffersResponseSchema:
    properties:
      counters:
        $ref: '#/definitions/my_offers.entities.get_offers.OfferCountersSchema'
      offers:
        items:
          $ref: '#/definitions/my_offers.entities.get_offers.GetOfferSchema'
        type: array
      page:
        $ref: '#/definitions/my_offers.entities.get_offers.PageInfoSchema'
    required:
    - counters
    - offers
    - page
    type: object
  my_offers.entities.get_offers.OfferCountersSchema:
    properties:
      active:
        format: int64
        title: active
        type: integer
      archived:
        format: int64
        title: archived
        type: integer
      declined:
        format: int64
        title: declined
        type: integer
      notActive:
        format: int64
        title: not_active
        type: integer
    required:
    - active
    - archived
    - declined
    - notActive
    type: object
  my_offers.entities.get_offers.PageInfoSchema:
    properties:
      canLoadMore:
        description: Это не последняя страница
        title: can_load_more
        type: boolean
      count:
        description: Количество  объектов
        format: int64
        title: count
        type: integer
      pageCount:
        description: Количество страниц
        format: int64
        title: page_count
        type: integer
    required:
    - canLoadMore
    - count
    - pageCount
    type: object
  my_offers.entities.get_offers.PaginationSchema:
    properties:
      limit:
        description: Количество объявлений на страницу
        format: int64
        title: limit
        type: integer
      offset:
        description: Отступ от начала
        format: int64
        title: offset
        type: integer
      page:
        description: Номер страницы начиная с 1
        format: int64
        title: page
        type: integer
    type: object
  my_offers.entities.get_offers.StatisticsSchema:
    properties:
      favorites:
        description: Количество добавлений в избранное
        format: int64
        title: favorites
        type: integer
      shows:
        description: Количество показов в поиске
        format: int64
        title: shows
        type: integer
      views:
        description: Количество просмотров карточки
        format: int64
        title: views
        type: integer
    type: object
  my_offers.entities.offer_view_model.AddressSchema:
    properties:
      name:
        description: Полный адрес
        title: name
        type: string
      searchUrl:
        description: Поисковый запрос по адресу
        title: search_url
        type: string
      type:
        enum:
        - country
        - district
        - house
        - location
        - road
        - street
        type: string
        x-country: Страна
        x-district: Район
        x-house: Дом
        x-location: Местоположение
        x-road: Шоссе
        x-street: Улица
    required:
    - name
    - searchUrl
    - type
    type: object
  my_offers.entities.offer_view_model.NewbuildingSchema:
    properties:
      name:
        description: Название ЖК
        title: name
        type: string
      searchUrl:
        description: Поисковый запрос по ЖК
        title: search_url
        type: string
    required:
    - name
    - searchUrl
    type: object
  my_offers.entities.offer_view_model.OfferGeoSchema:
    properties:
      address:
        description: Адрес
        items:
          $ref: '#/definitions/my_offers.entities.offer_view_model.AddressSchema'
        type: array
      newbuilding:
        $ref: '#/definitions/my_offers.entities.offer_view_model.NewbuildingSchema'
        description: Новостройки
      underground:
        $ref: '#/definitions/my_offers.entities.offer_view_model.UndergroundSchema'
        description: Метро
    type: object
  my_offers.entities.offer_view_model.PriceInfoSchema:
    properties:
      exact:
        description: Цена
        title: exact
        type: string
      range:
        description: Диапазон цен
        items:
          title: range
          type: string
        title: range
        type: array
    type: object
  my_offers.entities.offer_view_model.SubagentSchema:
    properties:
      id:
        description: ID агента
        format: int64
        title: id
        type: integer
      name:
        description: Полное имя агнета
        title: name
        type: string
    required:
    - id
    - name
    type: object
  my_offers.entities.offer_view_model.UndergroundSchema:
    properties:
      lineColor:
        description: Цвет линии метро
        title: line_color
        type: string
      name:
        description: Название метро
        title: name
        type: string
      regionId:
        description: ID региона
        format: int64
        title: region_id
        type: integer
      searchUrl:
        description: Поисковый запрос по метро
        title: search_url
        type: string
    required:
    - lineColor
    - name
    - regionId
    - searchUrl
    type: object
info:
  description: 'МКС: мои объявления для агента'
  title: my-offers
  version: 1.0.0
paths:
  /public/v1/get-offers/:
    post:
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/my_offers.entities.get_offers.GetOffersRequestSchema'
      produces:
      - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/my_offers.entities.get_offers.GetOffersResponseSchema'
        '400':
          schema:
            $ref: '#/definitions/cian_web.schemas.ErrorResponseSchema'
      summary: Получить получить объявления для пользователя. Для м/а с учетом иерархии.
swagger: '2.0'
